### ISSUE TITLE
Informational version standard

### ISSUE THREAD

**Issue by dcorriveau-omniscient** [SimpleGitVersion/CSemVer-Net#1]
Hi, I was wondering where I could find the documentation for the Informational version standard you are using ? From the tests, I can infer that the format should look like this:
`"1.2.3-prerelease (1.2.3-a) - SHA1: 0000000000000000000000000000000000000000 - CommitDate: 2017-06-27 08:27:35Z`
however I'm not sure where this format comes from. Do you have any links that would tell me the specs for that specific standard ?
I'm using [GitVersion](https://github.com/GitTools/GitVersion) to set the assembly info properties and the default format for the InformationalVersion is quite different (see the [documentation](http://gitversion.readthedocs.io/en/latest/configuration/#assembly-informational-format), you can also look at the sample [here](http://gitversion.readthedocs.io/en/latest/more-info/variables/)). Are you aware of that format ? Any plans to support it ?

Thanks !

**Comment by olivier-spinelli** [comment]
Hi,
Short answer: this format comes from my mind.
The way SimpleGitVersion works is quite different from GitVersion. In the last version of SimpleGitVersion, I extracted the CSemVer component and fixed/decided this format (that was previously loosely specified) based on the following rationales:
  - Guaranty reproductible builds (see https://reproducible-builds.org/). The Environment.UserName was previously included, I removed it.  
  - Fixed! So that parsing it back is included once for all in the CSemVer assembly (hence the InformationalVersion class).
  - Contains both SemVer and NuGetV2 version (even with the help of http://csemver.org/playground/site/ it is not that easy to instantly grab the association...).
  - Supports the SemVer Zero version (0.0.0-0 that is the absolute lowest possible SemVer - not CSemVer - version), and use it as a well-known default for any invalid build (dirty working folder, etc.)

I'm aware that this format is strongly tight to CSemVer/SimpleGitVersion. The intent of SimpleGitVersion is to remain simple, based on CSemVer. There are far more options in GitVersion, but actually we believe there are too much of them.

To answer your very last question, no, there is no plan to extend this, but I'd be happy to know your ideas about that and I'm opened to suggestions!

**Update:** We are not using GitVersion at all. SimpleGitVersionTask is the easiest (but currently works only for legacy csproj), For new csproj/.Net Core we use Cake (via CodeCake) and SimpleGitVersion.Cake. This is a sample of a typical build script (nearly copy/pasted between our projects): https://github.com/Invenietis/CK-Text/blob/master/CodeCakeBuilder/Build.cs

**Comment by dcorriveau-omniscient** [comment]
Thank you for the exhaustive answer.
I will look into integrating a parser specific to what I need (I'm not planning on switching the current format). This will be done in my fork (private) since I don't think we would want to add this functionality in CSemVer-Net anyway, judging from your answer you want to keep it lean with only the stuff related to SimpleGit / CSemVer.
Thanks !
